edgarezsb_sb:
    path:     /sb/{tabItem}
    defaults: { _controller: edgar_ez_site_builder.controller.sb:sbAction, tabItem: "dashboard" }
    requirements:
            tabItem: "[a-z]+"

edgarezsb_install_post:
    path: /sb/tab/install
    methods: [POST]
    defaults:
        _controller: edgar_ez_site_builder.controller.sb.install:installAction

edgarezsb_customer_post:
    path: /sb/tab/customer
    methods: [POST]
    defaults:
        _controller: edgar_ez_site_builder.controller.sb.customer:generateAction

edgarezsb_model_post:
    path: /sb/tab/model
    methods: [POST]
    defaults:
        _controller: edgar_ez_site_builder.controller.sb.model:generateAction

edgarezsb_site_post:
    path: /sb/tab/site
    methods: [POST]
    defaults:
        _controller: edgar_ez_site_builder.controller.sb.site:generateAction

