edgarezsb_dashboard:
    path:     /sb
    defaults: { _controller: edgar_ez_site_builder.controller.sb:dashboardAction }

edgarezsb_install:
    path: /sb/install
    defaults:
        _controller: edgar_ez_site_builder.controller.sb:tabInstallAction

edgarezsb_pjax:
    resource: "@EdgarEzSiteBuilderBundle/Resources/config/routing_pjax.yml"
    prefix:   /pjax

