smileezsb_sb:
    path:     /sb/{tabItem}
    defaults: { _controller: smile_ez_site_builder.controller.sb:sbAction, tabItem: "dashboard" }
    requirements:
            tabItem: "[a-z]+"

smileezsb_install_post:
    path: /sb/tab/install
    methods: [POST]
    defaults:
        _controller: smile_ez_site_builder.controller.sb.install:installAction

smileezsb_customer_post:
    path: /sb/tab/customer
    methods: [POST]
    defaults:
        _controller: smile_ez_site_builder.controller.sb.customer:generateAction

smileezsb_model_post:
    path: /sb/tab/model
    methods: [POST]
    defaults:
        _controller: smile_ez_site_builder.controller.sb.model:generateAction

smileezsb_modelactivate_post:
    path: /sb/tab/model/activate
    methods: [POST]
    defaults:
        _controller: smile_ez_site_builder.controller.sb.model:activateAction

smileezsb_site_post:
    path: /sb/tab/site
    methods: [POST]
    defaults:
        _controller: smile_ez_site_builder.controller.sb.site:generateAction

smileezsb_siteactivate_post:
    path: /sb/tab/site/activate
    methods: [POST]
    defaults:
        _controller: smile_ez_site_builder.controller.sb.site:activateAction

smileezsb_user_post:
    path: /sb/tab/user
    methods: [POST]
    defaults:
        _controller: smile_ez_site_builder.controller.sb.user:generateAction

