parameters:
    edgar_ez_site_builder.install.service.class: EdgarEz\SiteBuilderBundle\Service\InstallService
    edgar_ez_site_builder.customer.service.class: EdgarEz\SiteBuilderBundle\Service\CustomerService
    edgar_ez_site_builder.model.service.class: EdgarEz\SiteBuilderBundle\Service\ModelService
    edgar_ez_site_builder.site.service.class: EdgarEz\SiteBuilderBundle\Service\SiteService

services:
    edgar_ez_site_builder.install.service:
        class: %edgar_ez_site_builder.install.service.class%
        arguments:
            - @ezpublish.api.service.content_type
            - @edgar_ez_tools.contenttypegroup.service
            - @edgar_ez_tools.contenttype.service
            - @edgar_ez_tools.content.service

    edgar_ez_site_builder.customer.service:
        class: %edgar_ez_site_builder.customer.service.class%
        arguments:
            - @ezpublish.api.service.role
            - @ezpublish.api.service.location
            - @ezpublish.api.service.user
            - @ezpublish.api.service.content_type
            - @edgar_ez_tools.content.service
            - @edgar_ez_tools.role.service

    edgar_ez_site_builder.model.service:
        class: %edgar_ez_site_builder.model.service.class%
        arguments:
            - @ezpublish.api.service.url_alias
            - @ezpublish.api.service.location
            - @edgar_ez_tools.content.service

    edgar_ez_site_builder.site.service:
        class: %edgar_ez_site_builder.site.service.class%
        arguments:
            - @ezpublish.api.service.location
            - @ezpublish.api.service.url_alias
            - @edgar_ez_tools.content.service
