parameters:
    smile_ez_site_builder.install.service.class: Smile\EzSiteBuilderBundle\Service\InstallService
    smile_ez_site_builder.customer.service.class: Smile\EzSiteBuilderBundle\Service\CustomerService
    smile_ez_site_builder.model.service.class: Smile\EzSiteBuilderBundle\Service\ModelService
    smile_ez_site_builder.site.service.class: Smile\EzSiteBuilderBundle\Service\SiteService

    smile_ez_site_builder.project.task.service.class: Smile\EzSiteBuilderBundle\Service\Task\ProjectTaskService
    smile_ez_site_builder.customer.task.service.class: Smile\EzSiteBuilderBundle\Service\Task\CustomerTaskService
    smile_ez_site_builder.model.task.service.class: Smile\EzSiteBuilderBundle\Service\Task\ModelTaskService
    smile_ez_site_builder.site.task.service.class: Smile\EzSiteBuilderBundle\Service\Task\SiteTaskService
    smile_ez_site_builder.user.task.service.class: Smile\EzSiteBuilderBundle\Service\Task\UserTaskService
    smile_ez_site_builder.cache.task.service.class: Smile\EzSiteBuilderBundle\Service\Task\CacheTaskService
    smile_ez_site_builder.assets.task.service.class: Smile\EzSiteBuilderBundle\Service\Task\AssetsTaskService

    smile_ez_site_builder.mailer.class: Smile\EzSiteBuilderBundle\Mail\Sender

    smile_ez_site_builder.validator.modelname.class: Smile\EzSiteBuilderBundle\Form\Validator\Constraint\ModelNameConstraintValidator
    smile_ez_site_builder.validator.customername.class: Smile\EzSiteBuilderBundle\Form\Validator\Constraint\CustomerNameConstraintValidator
    smile_ez_site_builder.validator.host.class: Smile\EzSiteBuilderBundle\Form\Validator\Constraint\HostConstraintValidator
    smile_ez_site_builder.validator.hostsuffix.class: Smile\EzSiteBuilderBundle\Form\Validator\Constraint\HostSuffixConstraintValidator
    smile_ez_site_builder.validator.locationid.class: Smile\EzSiteBuilderBundle\Form\Validator\Constraint\LocationIDConstraintValidator
    smile_ez_site_builder.validator.sitename.class: Smile\EzSiteBuilderBundle\Form\Validator\Constraint\SiteNameConstraintValidator
    smile_ez_site_builder.validator.useremail.class: Smile\EzSiteBuilderBundle\Form\Validator\Constraint\UserEmailConstraintValidator
    smile_ez_site_builder.validator.username.class: Smile\EzSiteBuilderBundle\Form\Validator\Constraint\UserNameConstraintValidator
    smile_ez_site_builder.validator.vendorname.class: Smile\EzSiteBuilderBundle\Form\Validator\Constraint\VendorNameConstraintValidator

    smile_ez_site_builder.action_dispatcher.install.class: Smile\EzSiteBuilderBundle\Form\ActionDispatcher\InstallDispatcher
    smile_ez_site_builder.action_dispatcher.customer.class: Smile\EzSiteBuilderBundle\Form\ActionDispatcher\CustomerDispatcher
    smile_ez_site_builder.action_dispatcher.model.class: Smile\EzSiteBuilderBundle\Form\ActionDispatcher\ModelDispatcher
    smile_ez_site_builder.action_dispatcher.modelactivate.class: Smile\EzSiteBuilderBundle\Form\ActionDispatcher\ModelActivateDispatcher
    smile_ez_site_builder.action_dispatcher.site.class: Smile\EzSiteBuilderBundle\Form\ActionDispatcher\SiteDispatcher
    smile_ez_site_builder.action_dispatcher.siteactivate.class: Smile\EzSiteBuilderBundle\Form\ActionDispatcher\SiteActivateDispatcher
    smile_ez_site_builder.action_dispatcher.user.class: Smile\EzSiteBuilderBundle\Form\ActionDispatcher\UserDispatcher

    smile_ez_site_builder.controller.sb.class: Smile\EzSiteBuilderBundle\Controller\SbController
    smile_ez_site_builder.controller.sb.install.class: Smile\EzSiteBuilderBundle\Controller\InstallController
    smile_ez_site_builder.controller.sb.dashboard.class: Smile\EzSiteBuilderBundle\Controller\DashboardController
    smile_ez_site_builder.controller.sb.customer.class: Smile\EzSiteBuilderBundle\Controller\CustomerController
    smile_ez_site_builder.controller.sb.model.class: Smile\EzSiteBuilderBundle\Controller\ModelController
    smile_ez_site_builder.controller.sb.site.class: Smile\EzSiteBuilderBundle\Controller\SiteController
    smile_ez_site_builder.controller.sb.user.class: Smile\EzSiteBuilderBundle\Controller\UserController
    smile_ez_site_builder.tabs: [install, dashboard, customergenerate, modelgenerate, modelactivate, sitegenerate, siteactivate, usergenerate]

    smileezsb.security.service.class: Smile\EzSiteBuilderBundle\Service\SecurityService
    smileezsb.security.twig.extension.class: Smile\EzSiteBuilderBundle\Twig\Extension\SecurityExtension

services:
    smile_ez_site_builder.install.service:
        class: %smile_ez_site_builder.install.service.class%
        arguments:
            - @kernel
            - @ezpublish.api.service.content_type
            - @ezpublish.api.service.role
            - @ezpublish.api.service.location
            - @ezpublish.api.service.user
            - @ezpublish.api.service.language
            - @smile_ez_tools.contenttypegroup.service
            - @smile_ez_tools.contenttype.service
            - @smile_ez_tools.content.service
            - @smile_ez_tools.role.service

    smile_ez_site_builder.customer.service:
        class: %smile_ez_site_builder.customer.service.class%
        arguments:
            - @kernel
            - @ezpublish.api.service.role
            - @ezpublish.api.service.location
            - @ezpublish.api.service.user
            - @ezpublish.api.service.content_type
            - @smile_ez_tools.content.service
            - @smile_ez_tools.role.service
            - %ezpublish.siteaccess.groups%

    smile_ez_site_builder.model.service:
        class: %smile_ez_site_builder.model.service.class%
        arguments:
            - @kernel
            - @ezpublish.api.service.url_alias
            - @ezpublish.api.service.location
            - @ezpublish.api.service.role
            - @smile_ez_tools.content.service
            - @smile_ez_tools.role.service
            - @service_container

    smile_ez_site_builder.site.service:
        class: %smile_ez_site_builder.site.service.class%
        arguments:
            - @ezpublish.api.service.location
            - @ezpublish.api.service.url_alias
            - @ezpublish.api.service.content
            - @ezpublish.api.service.language
            - @smile_ez_tools.content.service
            - @smile_ez_tools.role.service

    # Task services
    smile_ez_site_builder.project.task.service:
        class: %smile_ez_site_builder.project.task.service.class%
        arguments:
            - @filesystem
            - @kernel
            - @ezpublish.api.service.location
            - @ezpublish.api.service.language
            - @smile_ez_site_builder.install.service
            - %kernel.root_dir%

    smile_ez_site_builder.customer.task.service:
        class: %smile_ez_site_builder.customer.task.service.class%
        arguments:
            - @filesystem
            - @kernel
            - @smile_ez_site_builder.customer.service
            - @ezpublish.api.service.language
            - @smile_ez_site_builder.mailer
            - %smile_ez_site_builder.sysadminemail%
            - %kernel.root_dir%

    smile_ez_site_builder.model.task.service:
        class: %smile_ez_site_builder.model.task.service.class%
        arguments:
            - @filesystem
            - @kernel
            - @smile_ez_site_builder.model.service
            - @ezpublish.api.service.location
            - @ezpublish.api.service.content
            - @ezpublish.api.service.language
            - %kernel.root_dir%

    smile_ez_site_builder.site.task.service:
        class: %smile_ez_site_builder.site.task.service.class%
        arguments:
            - @filesystem
            - @kernel
            - @ezpublish.api.service.location
            - @ezpublish.api.service.content
            - @ezpublish.api.service.user
            - @smile_ez_tools.role.service
            - @smile_ez_site_builder.site.service
            - @ezpublish.api.service.role
            - %kernel.root_dir%
        calls:
            - [setAnonymousUserID, [$anonymous_user_id;ezsettings$]]

    smile_ez_site_builder.user.task.service:
        class: %smile_ez_site_builder.user.task.service.class%
        arguments:
            - @smile_ez_site_builder.customer.service
            - @ezpublish.api.service.user
            - @ezpublish.api.service.location
            - @ezpublish.api.service.language
            - @smile_ez_site_builder.mailer
            - %smile_ez_site_builder.sysadminemail%

    smile_ez_site_builder.cache.task.service:
        class: %smile_ez_site_builder.cache.task.service.class%
        arguments:
            - @smileezsb.cache.clear
            - @kernel

    smile_ez_site_builder.assets.task.service:
        class: %smile_ez_site_builder.assets.task.service.class%
        arguments:
            - @kernel
            - @filesystem

    # tools services
    smile_ez_site_builder.mailer:
        class: %smile_ez_site_builder.mailer.class%
        arguments:
            - @swiftmailer.mailer

    # Form validators
    smile_ez_site_builder.validator.modelname:
        class: %smile_ez_site_builder.validator.modelname.class%
        tags:
            - { name: validator.constraint_validator, alias: smile_ez_site_builder.validator.modelname }

    smile_ez_site_builder.validator.customername:
        class: %smile_ez_site_builder.validator.customername.class%
        tags:
            - { name: validator.constraint_validator, alias: smile_ez_site_builder.validator.customername }

    smile_ez_site_builder.validator.host:
        class: %smile_ez_site_builder.validator.host.class%
        tags:
            - { name: validator.constraint_validator, alias: smile_ez_site_builder.validator.host }

    smile_ez_site_builder.validator.hostsuffix:
        class: %smile_ez_site_builder.validator.hostsuffix.class%
        tags:
            - { name: validator.constraint_validator, alias: smile_ez_site_builder.validator.hostsuffix }

    smile_ez_site_builder.validator.locationid:
        class: %smile_ez_site_builder.validator.locationid.class%
        tags:
            - { name: validator.constraint_validator, alias: smile_ez_site_builder.validator.locationid }

    smile_ez_site_builder.validator.sitename:
        class: %smile_ez_site_builder.validator.sitename.class%
        tags:
            - { name: validator.constraint_validator, alias: smile_ez_site_builder.validator.sitename }

    smile_ez_site_builder.validator.useremail:
        class: %smile_ez_site_builder.validator.useremail.class%
        tags:
            - { name: validator.constraint_validator, alias: smile_ez_site_builder.validator.useremail }

    smile_ez_site_builder.validator.username:
        class: %smile_ez_site_builder.validator.username.class%
        tags:
            - { name: validator.constraint_validator, alias: smile_ez_site_builder.validator.username }

    smile_ez_site_builder.validator.vendorname:
        class: %smile_ez_site_builder.validator.vendorname.class%
        tags:
            - { name: validator.constraint_validator, alias: smile_ez_site_builder.validator.vendorname }

    # Form action dispatchers
    smile_ez_site_builder.action_dispatcher.install:
        class: %smile_ez_site_builder.action_dispatcher.install.class%
        parent: ezrepoforms.action_dispatcher.base

    smile_ez_site_builder.action_dispatcher.customer:
        class: %smile_ez_site_builder.action_dispatcher.customer.class%
        parent: ezrepoforms.action_dispatcher.base

    smile_ez_site_builder.action_dispatcher.model:
        class: %smile_ez_site_builder.action_dispatcher.model.class%
        parent: ezrepoforms.action_dispatcher.base

    smile_ez_site_builder.action_dispatcher.modelactivate:
        class: %smile_ez_site_builder.action_dispatcher.modelactivate.class%
        parent: ezrepoforms.action_dispatcher.base

    smile_ez_site_builder.action_dispatcher.site:
        class: %smile_ez_site_builder.action_dispatcher.site.class%
        parent: ezrepoforms.action_dispatcher.base

    smile_ez_site_builder.action_dispatcher.siteactivate:
        class: %smile_ez_site_builder.action_dispatcher.siteactivate.class%
        parent: ezrepoforms.action_dispatcher.base

    smile_ez_site_builder.action_dispatcher.user:
        class: %smile_ez_site_builder.action_dispatcher.user.class%
        parent: ezrepoforms.action_dispatcher.base

    # controllers
    smile_ez_site_builder.controller.sb:
        class: %smile_ez_site_builder.controller.sb.class%
        arguments:
            - @ezpublish.api.service.location
            - @ezpublish.api.service.search
            - @ezpublish.api.service.language
            - @smile_ez_site_builder.install.service
            - %smile_ez_site_builder.tabs%
        parent: ezsystems.platformui.controller.base

    smile_ez_site_builder.controller.sb.install:
        class: %smile_ez_site_builder.controller.sb.install.class%
        arguments:
            - @smile_ez_site_builder.install.service
            - @smile_ez_site_builder.action_dispatcher.install
            - %smile_ez_site_builder.tabs%
            - @smileezsb.security.service
        parent: ezsystems.platformui.controller.base

    smile_ez_site_builder.controller.sb.dashboard:
        class: %smile_ez_site_builder.controller.sb.dashboard.class%
        arguments:
            - @doctrine
        parent: ezsystems.platformui.controller.base

    smile_ez_site_builder.controller.sb.customer:
        class: %smile_ez_site_builder.controller.sb.customer.class%
        arguments:
            - @smile_ez_site_builder.action_dispatcher.customer
            - %smile_ez_site_builder.tabs%
            - @smileezsb.security.service
        parent: ezsystems.platformui.controller.base

    smile_ez_site_builder.controller.sb.model:
        class: %smile_ez_site_builder.controller.sb.model.class%
        arguments:
            - @smile_ez_site_builder.action_dispatcher.model
            - @smile_ez_site_builder.action_dispatcher.modelactivate
            - %smile_ez_site_builder.tabs%
            - @smileezsb.security.service
            - @ezpublish.api.service.search
        parent: ezsystems.platformui.controller.base

    smile_ez_site_builder.controller.sb.site:
        class: %smile_ez_site_builder.controller.sb.site.class%
        arguments:
            - @ezpublish.api.service.location
            - @ezpublish.api.service.search
            - @smile_ez_site_builder.action_dispatcher.site
            - @smile_ez_site_builder.action_dispatcher.siteactivate
            - %smile_ez_site_builder.tabs%
            - @smileezsb.security.service
        parent: ezsystems.platformui.controller.base

    smile_ez_site_builder.controller.sb.user:
        class: %smile_ez_site_builder.controller.sb.user.class%
        arguments:
            - @smile_ez_site_builder.action_dispatcher.user
            - %smile_ez_site_builder.tabs%
            - @smileezsb.security.service
        parent: ezsystems.platformui.controller.base

    # security service
    smileezsb.security.service:
        class: %smileezsb.security.service.class%
        arguments:
            - @security.token_storage
            - @security.authorization_checker
            - @ezpublish.api.service.role

    # twig extensions
    smileezsb.security.twig.extension:
        class: %smileezsb.security.twig.extension.class%
        arguments:
            - @smileezsb.security.service
        tags:
            - { name: twig.extension }

    smileezsb.cache.clear:
        class: Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand
        calls:
            - [setContainer, ["@service_container"] ]
