parameters:
    edgar_ez_site_builder.install.service.class: EdgarEz\SiteBuilderBundle\Service\InstallService
    edgar_ez_site_builder.customer.service.class: EdgarEz\SiteBuilderBundle\Service\CustomerService
    edgar_ez_site_builder.model.service.class: EdgarEz\SiteBuilderBundle\Service\ModelService
    edgar_ez_site_builder.site.service.class: EdgarEz\SiteBuilderBundle\Service\SiteService

    edgar_ez_site_builder.project.task.service.class: EdgarEz\SiteBuilderBundle\Service\Task\ProjectTaskService
    edgar_ez_site_builder.customer.task.service.class: EdgarEz\SiteBuilderBundle\Service\Task\CustomerTaskService
    edgar_ez_site_builder.model.task.service.class: EdgarEz\SiteBuilderBundle\Service\Task\ModelTaskService
    edgar_ez_site_builder.site.task.service.class: EdgarEz\SiteBuilderBundle\Service\Task\SiteTaskService

    edgar_ez_site_builder.mailer.class: EdgarEz\SiteBuilderBundle\Mail\Sender

    edgar_ez_site_builder.controller.sb.class: EdgarEz\SiteBuilderBundle\Controller\SbController
    edgar_ez_site_builder.tabs: [install, dashboard, customergenerate, modelgenerate, sitegenerate, siteactivate]

services:
    edgar_ez_site_builder.install.service:
        class: %edgar_ez_site_builder.install.service.class%
        arguments:
            - @kernel
            - @ezpublish.api.service.content_type
            - @ezpublish.api.service.role
            - @ezpublish.api.service.location
            - @ezpublish.api.service.user
            - @edgar_ez_tools.contenttypegroup.service
            - @edgar_ez_tools.contenttype.service
            - @edgar_ez_tools.content.service
            - @edgar_ez_tools.role.service

    edgar_ez_site_builder.customer.service:
        class: %edgar_ez_site_builder.customer.service.class%
        arguments:
            - @kernel
            - @ezpublish.api.service.role
            - @ezpublish.api.service.location
            - @ezpublish.api.service.user
            - @ezpublish.api.service.content_type
            - @edgar_ez_tools.content.service
            - @edgar_ez_tools.role.service
            - %ezpublish.siteaccess.groups%

    edgar_ez_site_builder.model.service:
        class: %edgar_ez_site_builder.model.service.class%
        arguments:
            - @kernel
            - @ezpublish.api.service.url_alias
            - @ezpublish.api.service.location
            - @ezpublish.api.service.role
            - @edgar_ez_tools.content.service
            - @edgar_ez_tools.role.service
            - %ezpublish.siteaccess.groups%
            - @service_container

    edgar_ez_site_builder.site.service:
        class: %edgar_ez_site_builder.site.service.class%
        arguments:
            - @ezpublish.api.service.location
            - @ezpublish.api.service.url_alias
            - @edgar_ez_tools.content.service
            - @edgar_ez_tools.role.service

    edgar_ez_site_builder.project.task.service:
        class: %edgar_ez_site_builder.project.task.service.class%

    edgar_ez_site_builder.customer.task.service:
        class: %edgar_ez_site_builder.customer.task.service.class%

    edgar_ez_site_builder.model.task.service:
        class: %edgar_ez_site_builder.model.task.service.class%

    edgar_ez_site_builder.site.task.service:
        class: %edgar_ez_site_builder.site.task.service.class%

    edgar_ez_site_builder.mailer:
        class: %edgar_ez_site_builder.mailer.class%
        arguments:
            - @swiftmailer.mailer

    edgar_ez_site_builder.controller.sb:
        class: %edgar_ez_site_builder.controller.sb.class%
        arguments:
            - %edgar_ez_site_builder.tabs%
        parent: ezsystems.platformui.controller.base
