system:
    default:
        yui:
            modules:
                smileezsb-sbapplugin: # should match the first parameter of YUI.add
                    requires: ['ez-pluginregistry', 'plugin', 'base', 'smileezsb-sbview', 'smileezsb-sbviewservice'] # depends on the plugin code
                    dependencyOf: ['ez-platformuiapp']
                    path: %smile_ez_site_builder.public_dir%/js/apps/plugins/smileezsb-sbappplugin.js
                smileezsb-navigationplugin:
                    requires: ['ez-pluginregistry', 'ez-viewservicebaseplugin', 'ez-navigationitemview']
                    dependencyOf: ['ez-navigationhubviewservice']
                    path: %smile_ez_site_builder.public_dir%/js/views/services/plugins/smileezsb-navigationplugin.js
                smileezsb-sbviewservice:
                    requires: ['ez-serversideviewservice']
                    path: %smile_ez_site_builder.public_dir%/js/views/services/smileezsb-sbviewservice.js
                smileezsb-sbview:
                    requires: ['ez-serversideview']
                    path: %smile_ez_site_builder.public_dir%/js/views/smileezsb-sbview.js


